fix: fixed rcs channel to point to v2 of ZenviaAPI
zenvia/zenvia-sdk-node pull request #23
Opened 2021-05-28 16:36 UTC by victorshp

**Jira Link** => https://zenvia.atlassian.net/browse/CON-205?atlOrigin=eyJpIjoiMjZkODcwNTc0MTExNGM5ZjgwODRkMTU1NmQ1MjE0OTQiLCJwIjoiaiJ9**

**Problem**
All channels were sending message through v1 using this SDK written in node (subscriptions/webhooks too).

**Diagnostic**
Channels and subscriptions (webhooks) needed to be fixed to point to v2 path of Zenvia's API, not V1.

**Implementation**

- All channels and subscriptions points to v2
- Tests adjusted to the above implementation
- v2.0.0 tag added through Git
- PackageJSON from 1.5.0 to 2.0.0

2021-05-28 20:59 UTC, rafael-org commented on package.json
> +  "version": "1.5.1",
Lembrando 2.0.0 em vez de 1.5.1

2021-05-28 21:00 UTC, rafael-org commented on src/lib/channels/abstract-channel.ts
> -    const path = `/v1/channels/${this.channel}/messages`;
Lembrando também que é v2 pra todos os canais.

2021-05-28 21:00 UTC, rafael-org commented on test/lib/client.spec.ts
> +        .post('/v2/channels/rcs/messages', expectedMessage)
Lembrando que vai ter que atualizar os testes de todos os canais.

2021-05-28 21:02 UTC, rafael-org commented on package.json
> +  "version": "1.5.1",
além disso, no SDK tem uma parte que faz subscrição automática, muda isso pra v2 também.

2021-05-28 21:17 UTC, wmangelardo commented on src/lib/channels/abstract-channel.ts
> +    }
OMG, I wrote the comment but did not push review... 🤦
Due to @rafael-org comments, the whole sdk should work on version 2 of the API.

2021-05-28 21:54 UTC, rafael-org requested changes
O itens que eu comentei e o Wladi:
- /v2 pra tudo, nada de if de canal
- package 2.0.0, casa com a versão da API e não corre risco de quebrar nenhum cliente com o update automático que o npm install faz.
- Também atualizar a parte do SDK que cria webhook automáticamente pra criar webhooks na versão 2.

2021-05-31 00:57 UTC, victorshp commented
@rafael-org comitei as mudanças necessárias no PR. Só queria anotar aqui que reports e templates ainda apontam para v1.

2021-05-31 02:33 UTC, rafael-org commented
> @rafael-org comitei as mudanças necessárias no PR. Só queria anotar aqui que reports e templates ainda apontam para v1.

Muda tudo pro v2! Versão 2 do SDK aponta pra versão 2 da API! Porque a hesitação em mudar? Muda tudo!

2021-06-01 12:28 UTC, victorshp commented
@rafael-org done

2021-06-01 20:18 UTC, rafael-org approved these changes
Ah, eu testei, o padrão já é v2 pra subscriptions.

2021-06-02 12:59 UTC, merged